spring:
  datasource:
    driver-class-name: org.h2.Driver  # Database? H2? ?????.
    url: jdbc:h2:tcp://localhost/~/test7  # H2 ?? ??
    username: sa  # H2 ?? ? ??? username ?? (??? ??? ??)
    password: 1 # H2 ?? ? ??? password ?? (??? ??? ??)
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        # ddl-auto: create
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace


